<a href="https://colab.research.google.com/github/hemil19/nlp-projects/blob/master/Word_Embedding_in_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

#OneHotRepresentation

In [5]:
onehot_repr=[one_hot(words,voc_size) for words in sent] 
print(onehot_repr)

[[1473, 987, 4686, 6], [1473, 987, 4686, 9268], [1473, 836, 4686, 9055], [2233, 7288, 8955, 8523, 7243], [2233, 7288, 8955, 8523, 4487], [7909, 1473, 9187, 4686, 6487], [9475, 9840, 6492, 8523]]


#Word Embedding Represntation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1473  987 4686    6]
 [   0    0    0    0 1473  987 4686 9268]
 [   0    0    0    0 1473  836 4686 9055]
 [   0    0    0 2233 7288 8955 8523 7243]
 [   0    0    0 2233 7288 8955 8523 4487]
 [   0    0    0 7909 1473 9187 4686 6487]
 [   0    0    0    0 9475 9840 6492 8523]]


In [12]:
#dimension=features
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

array([[[ 0.04357995,  0.04895058,  0.01914642,  0.04073628,
          0.00963452,  0.0473406 ,  0.02351179, -0.01829856,
         -0.01636494, -0.0344064 ],
        [ 0.04357995,  0.04895058,  0.01914642,  0.04073628,
          0.00963452,  0.0473406 ,  0.02351179, -0.01829856,
         -0.01636494, -0.0344064 ],
        [ 0.04357995,  0.04895058,  0.01914642,  0.04073628,
          0.00963452,  0.0473406 ,  0.02351179, -0.01829856,
         -0.01636494, -0.0344064 ],
        [ 0.04357995,  0.04895058,  0.01914642,  0.04073628,
          0.00963452,  0.0473406 ,  0.02351179, -0.01829856,
         -0.01636494, -0.0344064 ],
        [-0.03323211, -0.03321022,  0.03555882, -0.02063085,
          0.04077924,  0.049864  ,  0.0415214 ,  0.00435158,
         -0.0125209 , -0.02857678],
        [-0.0261922 ,  0.00280315,  0.04334083,  0.03904134,
          0.02762244, -0.00378373, -0.0474023 , -0.03269204,
          0.02223134,  0.02012861],
        [ 0.03397295, -0.01155766,  0.04053258, -0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 1473,  987, 4686,    6], dtype=int32)

In [20]:
model.predict(embedded_docs[0])

array([[[ 0.04357995,  0.04895058,  0.01914642,  0.04073628,
          0.00963452,  0.0473406 ,  0.02351179, -0.01829856,
         -0.01636494, -0.0344064 ]],

       [[ 0.04357995,  0.04895058,  0.01914642,  0.04073628,
          0.00963452,  0.0473406 ,  0.02351179, -0.01829856,
         -0.01636494, -0.0344064 ]],

       [[ 0.04357995,  0.04895058,  0.01914642,  0.04073628,
          0.00963452,  0.0473406 ,  0.02351179, -0.01829856,
         -0.01636494, -0.0344064 ]],

       [[ 0.04357995,  0.04895058,  0.01914642,  0.04073628,
          0.00963452,  0.0473406 ,  0.02351179, -0.01829856,
         -0.01636494, -0.0344064 ]],

       [[-0.03323211, -0.03321022,  0.03555882, -0.02063085,
          0.04077924,  0.049864  ,  0.0415214 ,  0.00435158,
         -0.0125209 , -0.02857678]],

       [[-0.0261922 ,  0.00280315,  0.04334083,  0.03904134,
          0.02762244, -0.00378373, -0.0474023 , -0.03269204,
          0.02223134,  0.02012861]],

       [[ 0.03397295, -0.01155766,  0.04